### ISSUE TITLE
Discord Button Shifts Off-Page at 1024-1040px Screen Width

### ISSUE THREAD

**Issue by vvzuev** [discord-python/site#1015]
Summary: When the screen width is between 1024 and 1040 pixels, the Discord button shifts to the right beyond the edge of the main page.

Environment: win10, screen resolution 1024x768, browser: Chrome 114 latest

Step to reproduse: 1. Open a web browser.
                               2. Enter the URL https://www.pythondiscord.com/ in the address bar.

![Discord button 2](https://github.com/python-discord/site/assets/51853424/961bc87f-a894-4136-acab-e2cc029b5426)

**Comment by ChrisLovering** [comment]
I've tried emulating this with a 1024x768 viewport on both chrome & firefox but could not reproduce. You mentioned that chrome is on the latest version, but i see that there is an `Update` message in the top right. Could you update and try again?

If that still doesn't work, could you open console and run `console.log($(window).width(), $(window).height())` and send the results here?

Providing a list of extensions you have enabled, if any, would be useful too.

**Comment by vvzuev** [comment]
Output from the console:
console.log($(window).width(), $(window).height())
VM308:1 Uncaught TypeError: Cannot read properties of undefined (reading 'width')
    at <anonymous>:1:22
(anonymous) @ VM308:

The previous screenshot was taken in browserstack, and here is another one from my browser:

![Discord Button 3](https://github.com/python-discord/site/assets/51853424/e4a17ea2-a4cd-4cec-b22a-740bbe3a1d43)

**Comment by wookie184** [comment]
I can also reproduce this. The main solutions I can think of are:
- Collapse to using a hamburger menu a bit sooner.
- Somehow reduce the padding on each of the navigation buttons when they don't fit. I don't think we want it to look different at larger sizes so they would need to only be closer when it doesn't fit.

The first sounds like it should be easier.

**Comment by sarzz2** [comment]
Hi, I'd like to work on this

**Comment by jchristgit** [comment]
Hi @sarzz2, thanks for your interest in this issue :slightly_smiling_face: I have assigned you, let me know if you need help.

**Comment by sarzz2** [comment]
Hello @jchristgit So if we try to implement the first solution "Collapse to using a hamburger menu a bit sooner." would be a bigger/more difficult change since the site is using Bulma to decide when to use a hamburger menu.
We would need to override various existing Bulma CSS classes, I have tried and haven't been able to do so successfully yet.

**My proposal:-**
Right now the discord button on the top right(which is causing the issue) has the following properties(in **base.css**):-
```
#discord-btn a {
    color: transparent;
    background-image: url(../../images/navbar/discord.svg);
    background-size: 200%;
    background-position: 100% 50%;
    background-repeat: no-repeat;
    padding-left: 2.5rem;
    padding-right: 2.5rem;
    background-color: #697ec4ff;
    margin-left: 0.5rem;
    transition: all 0.2s cubic-bezier(.25,.8,.25,1);
    overflow: hidden;
}
```
**Solution:-**
1. Reduce the ```padding-right``` from ```2.5``` to ```2.2```
2. Remove ```margin-left``` property or ```reduce``` it to ```0.1``` or completely remove it to avoid inconsistency.

I have tested both scenarios and it'll fix the offset and the page will look like this:-

<img width="1355" alt="Screenshot 2023-10-05 at 12 23 42 PM" src="https://github.com/python-discord/site/assets/45039724/d09e01e7-74bd-4a2e-b1af-749e5d75c7fd">

**Comment by jchristgit** [comment]
@sarzz2 I think that looks good. If you open a pull request we can check this out on a deploy preview?
