### ISSUE TITLE
Truncated Dropdown Menu Items in the Sub-Articles Section

### ISSUE THREAD

**Issue by vvzuev** [discord-python/site#1037]
Summary: In the "Sub-Articles" section of the "Contributing" page, when the dropdown menu is expanded, some section names are cut off at the right edge of the page. This requires users to horizontally scroll the page to read them completely, which can lead to a poor user experience.

URL: https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/

Environment: windows 10, display resolution: 1920х1080, browsers: Chrome, Firefox

Step to reproduse: 
1.  Navigate to the "Contributing" page.
2. Locate the "Sub-Articles" section at the top right of the page.
3. Click on the "Sub-Articles" dropdown menu to expand it.
4. Observe the section names at the right edge of the expanded dropdown menu.

Expected Result: All section names in the dropdown menu should be fully visible without requiring horizontal scrolling.

Actual Result: Some section names in the dropdown menu are cut off at the right edge of the page, requiring users to horizontally scroll to read them completely.

Attachment:

![Contributing2](https://github.com/python-discord/site/assets/51853424/d6044abe-9587-4d09-b206-919bbbd4c2b2)

https://github.com/python-discord/site/assets/51853424/6b14ed2a-279b-4a53-acac-d12a52cb4d1b

**Comment by sarzz2** [comment]
I have identified the issue, it's due to the **whitespace** property of a.dropdown-item

Simple fix:-
- Remove the whitespace:no-wrap property however that would cause the menu item to look like the ss below

If the options needs to be in a single line then multiple CSS properties would need to be changed I imagine as I could not get it to work by playing around with some of the element properties only

<img width="1355" alt="image" src="https://github.com/python-discord/site/assets/45039724/3997bef5-5f4a-4942-8466-dd4e4dd4d8d7">

**Comment by sarzz2** [comment]
Does this need fixing? Can i work on this?

**Comment by jchristgit** [comment]
Yep it does. Thank you for your interest, I've assigned you. Let me know if you need any pointers :slightly_smiling_face:
