### ISSUE TITLE
Improve accessibility

### ISSUE THREAD

**Issue by Anonymous4045** [discord-python/site#1363]
I have identified numerous accessibility issues throughout the website. I believe addressing these issues could greatly improve the user experience of people with certain disabilities.

This [Google Drive folder](https://drive.google.com/drive/folders/1PTQQnUwLcFOKL-rKFjxm2102wpW9BmI8) contains an overview, a spreadsheet of the issues found, and some screenshots.

**Comment by jb3** [comment]
We'd rather not have people download potentially insecure files to triage this issue.

Please upload to an online document provider such as Google Docs or convert to a single PDF. I am editing those links out of the initial comment.

**Comment by Anonymous4045** [comment]
Alright, here's a Google Drive link instead: https://drive.google.com/drive/folders/1PTQQnUwLcFOKL-rKFjxm2102wpW9BmI8

**Comment by jchristgit** [comment]
Thank you very much for the extensive audit!

I have went ahead and created issues for each of these items, matching the priority you put into the document. Everything except for the "Advisory" priority is something I would classify as a bug, since the page isn't working like it should.

The milestone https://github.com/python-discord/site/milestone/1 tracks all issues related to it.

**Comment by jchristgit** [comment]
I'm going to close this since all the individual items from the planning have been put into individual tickets now, thank you very much again :slightly_smiling_face:
