### ISSUE TITLE
Show channel info in message logs

### ISSUE THREAD

**Issue by mbaruh** [discord-python/site#620]
Currently when messages are deleted by the anti-spam filter or by the clean command, a message log is created with info of of the user who sent it, at what time, and the contents of each message.

With recent developments, these two features now work across multiple channels, but the logs don't include that information making them sometimes hard to follow. 

Including the channel ID for each message seems to make sense, but at the same time we navigate channels using their names. Perhaps we include both?

**Comment by jchristgit** [comment]
We currently do not synchronize channels with the names, so the channel IDs would be natural here.

To have the channel names here, we would either have to:

- Use metricity (it is a bit messy, in my opinion)
- Call to Discord (would require embedding an API key in the site)
- Synchronizing channel names from bot with site

Having channel IDs on its own would be nice, but we would REALLY be helped a LOT by channel names.

**Comment by sue-m-oh** [comment]
If having the channel names in the logs is a hindrance, I've changed my mind and think that just having the channel IDs will suffice.

**Comment by TizzySaurus** [comment]
After discussing this a bit in internal mod channels, I've decided I'd like to have a go at implementing this (with the approach of just using channel IDs, since I think the channel is something we need to reference little enough that the mild inconvenience of having to copy it and type <#channel_id> inside Discord to get the name is acceptable).

From what I can tell, the bot side of this is already implemented, as the payload when getting a clean log link actually passes the channel id of each message (see [here](https://github.com/python-discord/bot/blob/91621bc7ef590118e91bbb2e387db5e14128b530/bot/exts/moderation/modlog.py#L61-L71)).

As such, this should just be a case of updating the [DeletedMessage](https://github.com/python-discord/site/blob/9d1ea1667d501e515957909d5c261525ff6aeaa6/pydis_site/apps/api/models/bot/deleted_message.py#L7-L14) class, and then updating [the log html file](https://github.com/python-discord/site/blob/main/pydis_site/templates/staff/logs.html).

Edit: in fact, I'm not sure we even need to updated the DeletedMessage class. We may be able to just do `message.channel_id` within the html file.
