### ISSUE TITLE
Add code jam winners for summer code jam 2022

### ISSUE THREAD

**Issue by jchristgit** [discord-python/site#911]
https://www.pythondiscord.com/events/code-jams/8/ has the winners on the webpage, https://www.pythondiscord.com/events/code-jams/9/ has not. We should add it and make it clear that the code jam has finished.

**Comment by r4gesingh47** [comment]
Can i pick this on?. I have experience with Django but not that much with front end but I think should be possible.

**Comment by ChrisLovering** [comment]
Sure, assigned! All the codejam content can be found in this folder.
https://github.com/python-discord/site/tree/main/pydis_site/templates/events/pages/code-jams

This guide should get you setup and running with the site
https://www.pythondiscord.com/pages/guides/pydis-guides/contributing/site/

**Comment by r4gesingh47** [comment]
Hi had a few question( In comparison with the page for google jam8)

 1. Unable to find the team member names for the winners, so should I remove that block.

 2.  Code Jam 8 had an submissions page as well but we don't have it for code jam 9 ( if we want to add it if yes then where I can find the data.

**Comment by wookie184** [comment]
Hi, thanks for working on this! Here's the information on team members and submissions, I think a submissions page would be good if you're happy to add it.

Team members:
- Cerebral Centaurs: Palmirka, Tu®tle, collerek, Rortox
- Kingly Kelpies: Kingu, Falkan, Bamboodja, Redriel, Vinyzu
- Logical Leprechauns: Fyx, Aboo Minister, A5rocks, Bautista, ~tylerr


Submissions (there was one more, from the "Sensational Sirens" but I removed it because the link 404d):

- Artful Angels	https://github.com/Artful-Angels/code-jam
- Burly Barghests	https://github.com/jasonho1308/summer-code-jam-2022
- Cerebral Centaurs	https://github.com/collerek/cerebral-centaurs
- Dynamic Dryads	https://github.com/Kronifer/code-jam-9
- Generous Giants	https://github.com/bast0006/cj9-generous-giants/
- Genuine Djinn	https://github.com/srijal30/genuine-djinn
- Gorgeous Ghouls	https://github.com/Gorgeous-Ghouls/Blak
- Heroic Hydra	https://github.com/mkadiya20/heroic-hydra
- Kindly Kappa	https://github.com/Vthechamp22/kindly-kappa
- Kingly Kelpies	https://github.com/Kingly-elpies/KinglyKelpies
- Logical Leprechauns	https://github.com/AbooMinister25/Curse-of-the-Mites
- Lucky Leucrota	https://github.com/lucky-leucrota/cj9-lucky-leucrota
- Muscular Mermaids	https://github.com/vonvic/Python-CodeJam-2022-MM
- Old-Fashioned Orcs	https://github.com/smileyface12349/old-fashioned-orcs
- Sassy Snallygasters	https://github.com/SFM61319/sassy-snallygasters_code-jam-9
- Silly Selkies	https://github.com/kguzek/code-jam-2022
- Spiffy Sphinxes	https://github.com/Sanyok6/Chesstopia
- Stately Satyrs	https://github.com/Lime-Parallelogram/cj2022-stately-satyrs
- Tireless Timingila	https://github.com/Ibrahim2750mi/tireless-timingila
- Towering Tupilaqs	https://github.com/TheFactoryMustGrowLarger/towering-tupilaqs
- Valiant Valkyries	https://github.com/legosiv/valiant-valkyries
- Wily Werewolves	https://github.com/HarshitJoshi9152/Codejam-2022-pythondiscord
- Zesty Zombies	https://github.com/nitinramvelraj/zesty-zombies-2.0

**Comment by r4gesingh47** [comment]
Added the submission page as well.
https://github.com/python-discord/site/pull/952
